version: "3.8"

services:
   frontend:
    build: ./frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    environment:
      - PORT=80